---
seed: 314159628
means: [[0, -10], [-9, 7], [9, 5], [-7, -9], [-10, 0]]
stds: [[0.5, 0.5], [0.5, 0.5], [0.5, 0.5], [0.5, 0.5], [0.5, 0.5]]
n: 50
agreement: 5
figure_output_path: "figures/full-triplets"
num_distance_function_samples: 10
